urls.py
from django.conf.urls.defaults import *
from katok.main.views import pages, comment, view_gallery
from katok.main import views

#current_datetime
from django.conf import settings
if settings.DEBUG:


# Uncomment the next two lines to enable the admin:
    from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^katok/', include('katok.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
     #(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     
     (r'^admin/', include(admin.site.urls)),
     
     #(r'^time/$', current_datetime),
     
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
            
        (r'^robots.txt$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'path': "robots.txt"}),
            
        (r'^favicon.ico$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'path': "favicon.ico"}),
            
 #       (r'^media/(?P<path>.*)$', 'django.views.static.serve',(r'^gallery/$', pages, {'template_name': 'gallery.html'}),
 #           {'document_root': settings.MEDIA_ROOT}),
     
     
     
     
     (r'^$', pages, {'template_name': 'index.html'}),
     (r'^index/$', pages, {'template_name': 'index.html'}),
     (r'^index.htm/$', pages, {'template_name': 'index.html'}),
     (r'^index.html/$', pages, {'template_name': 'index.html'}),
     (r'^price/$', pages, {'template_name': 'price.html'}),
     (r'^gallery/$', view_gallery),       
     (r'^contacts/$', pages, {'template_name': 'contacts.html'}),       
     (r'^comment/$', comment),
     
     
     
 #        (r'^search-form/$', views.search_form),
 #   (r'^search/$', views.search),    
)

main/models.py
#coding: utf-8

from django.db import models
import datetime
import os
# Create your models here.
class Record(models.Model):
    name = models.CharField('Имя', max_length=30)
    text = models.TextField('Текст', max_length = 2000)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        verbose_name = 'отзыв'
        verbose_name_plural = 'отзывы'
        
def make_upload_path(instance, filename):
    now = datetime.datetime.now()
    path, ext = os.path.splitext(filename)
    fn = "f%s%s%s%s%s%s"%(now.year, now.month, now.day, now.hour, now.minute, now.second)
    return "uploads/%s%s"%(fn, ext)

class Gallery(models.Model):
    name = models.CharField('Название галереи', max_length = 300)
    date_created = models.DateTimeField('Время создания', auto_now_add = True)

    class Meta:
        ordering = ('-date_created', )
        verbose_name = 'фотогалерея'
        verbose_name_plural = 'фотогалереи'

    def __unicode__(self):
        return self.name

    def get_fotos(self):
        return Foto.objects.filter(gallery__id = self.id)

class Foto(models.Model):
    gallery = models.ForeignKey(Gallery, verbose_name = 'Фотогалерея')
    foto = models.ImageField('Фото', upload_to = make_upload_path)
    comment = models.CharField('Примечание', max_length = 300)
    date_created = models.DateTimeField('Время создания', auto_now_add = True)

    def __unicode__(self):
        return '%s - %s' % (self.gallery.name, self.comment)

    class Meta:
        ordering = ('-date_created', )
        verbose_name = 'фото'
        verbose_name_plural = 'фотографии'

sorl/thumbnail/models.py
# Needs a models.py file so that tests are picked up.

main/forms.py
# -*- coding:utf-8 -*-

from django import forms
from models import Record

class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
    

main/views.py
#coding: utf-8

from django.shortcuts import render_to_response
from django.template import RequestContext
from django.db import models
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from models import Record, Foto, Gallery

from django.conf import settings

from django.http import HttpResponseRedirect

from django.core.mail import send_mail
from katok.main.forms import RecordForm

def get_page(request, klass, count):
    paginator = Paginator(klass.objects.all(), count)

    try:
        page_number = int(request.GET.get('page', '1'))
    except ValueError:
        page_number = 1

    try:
        page = paginator.page(page_number)
    except (EmptyPage, InvalidPage):
        page = paginator.page(paginator.num_pages)

    return (page, page_number)


def pages(request, template_name):
    return render_to_response(template_name, context_instance=RequestContext(request))


def comment(request):
     if request.method == 'POST':
        form = RecordForm(request.POST)
        if form.is_valid():
            new_comment = form.save()        
            return HttpResponseRedirect('/comment/')
        
     else:
         form = RecordForm()
         
     comments = Record.objects.all()
    
     return render_to_response('comment.html', {'form': form, 'comments': comments}, context_instance=RequestContext(request))   
    
def view_gallery(request):
    page, page_number = get_page(request, Gallery, settings.GALLERY_COUNT)
    return render_to_response('gallery.html', {'gallery': True, 'page': page, 'page_number': page_number},
                              context_instance=RequestContext(request))

templates/comment.html
{% include 'header.html' %}
 <!-- Content All Starts-->  
 
 <div id="content_all">

<p>  <font color="#ffffff"> На данной странице отзывы о Ледовом катке на Проспекте: </font> </p>
 
   
    {% for Record in comments %}
       <p> Отзыв № {{ Record.id }}. Оставил посетитель - {{ Record.name }}<br>  {{ Record.text  }} </p>
		{% empty %}
           <p>Никто еще не оставлял комментариев</p>
        {% endfor %}
 		<hr>
	      	
    {% if form.errors %}
        <p style="color: red;">
            Пожалуйста, исправьте ошибки ниже.
        </p>
    {% endif %}

    <form action="./" method="post"> {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Отправить">
    </form>
   
    <div style="height: 230px"> </div>
 </div>
 
<!-- Content All Ends--> 
{% include 'footer.html' %}

templates/contacts.html
{% include 'header.html' %}
 <!-- Content All Starts-->  
 <div id="content_all">

   <p>Каток расположен по адресу:</p>
   <p>Ул. Проспект Октября 91а, за клубом Проспект на остановке Гимназия им. Гарипова (Юрюзань). 
   Проезд осуществляется следующими маршрутами: </p>
   <p>Троллейбусы: 1, 2, 8, 11, 13, 14, 22 </br>
Автобусы: 14, 26, 51, 51а, 59, 59э, 69, 69с, 74, 164т </br>
Маршрутные такси: 8с, 22, 25, 36, 71, 131к, 164к, 180, 203, 211, 216, 216а, 223, 224, 226, 228, 233, 239, 244, 245, 247, 247, 249, 258, 261б, 269, 270, 272, 277, 279, 289, 290, 298</p>
   
   <div id="cont">
   <div id="YMapsID" style="width:600px;height:400px" ></div>
   </div>
   
  <div style="height: 230px"> </div>
   
 </div>
<!-- Content All Ends-->  
{% include 'footer.html' %}


templates/current_datetime.html
<html><body>It is now {{ current_date }}.</body></html>

templates/footer.html
<div style="text-align:center; padding:20px;">




</div>
</div>
<!-- WRAP DIV ENDS -->

<!-- FOOTER-ALL-BG DIV STARTS -->

<div id="footer-all-bg">
   <div id="footer_all">
       <div id="footer_top">
	   <!-- Footer Box Top -->
	     <div class="footer_top_boxes">
	     
<!-- Footer Box Ends --> 
		<!-- Footer Box Top --><!-- Footer Box Ends --> 
		<!-- Footer Box Top --><!-- Footer Box Ends --><!-- FOOTER-ALL-BG DIV ENDS -->


</body>
</html>

templates/gallery.html
{% include 'header.html' %} 
 <!-- Content All Starts-->  

{% block content %}
    <div class="span-19 last" id="gallery">
  
        <div class="span-19 last">
            {% load thumbnail %}
            {% for gal in page.object_list %}
                <div class="one_gallery">
                    <h2> {{gal.name }} </h2>
                    <h3> Создан {{gal.date_created|date:"d.m.Y"}} </h3>
                    <div class="gcontainer">
                        {% for foto in gal.foto_set.all %}
                        <a class="pics" href="/media/{{foto.foto}}"> <img src="{% thumbnail foto.foto 150x150 %}" alt="{{foto.comment}}" /> </a>
                        {% empty %}
                        В этой галерее нет фотографий
                        {% endfor %}
                    </div>
                </div>                
            {% empty %}
                Фотографии еще не добавлены
            {% endfor %}

        </div>
    </div>
	
{% endblock %}

  <div style="padding: 230px"> </div>

{% include 'footer.html' %}

templates/header.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" dir=" LTR" lang ="ru">
<html xmlns="http://www.w3.org/1999/xhtml">
<head profile="http://gmpg.org/xfn/11">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Каток на проспекте</title>

<link rel="stylesheet" href="{{ MEDIA_URL }}css/style.css" type="text/css" media="screen, projection" />
<link rel="icon" href="{{ MEDIA_URL }}n.ico" type="image/x-icon"/>
<script type="text/javascript" language="javascript" src="{{ MEDIA_URL }}js/jquery-1.4.1.min.js"></script>
<script src="{{ MEDIA_URL }}js/all_js.js" type='text/javascript'></script>

<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="wp-includes/wlwmanifest.xml" /> 
<link rel='index' title='КАТОКнаПРОСПЕКТЕ.рф' href='/' />

<script src="http://api-maps.yandex.ru/1.1/index.xml?key=AJUWPE0BAAAAaaIlTwIAHi8fyjxbMKvnwAoC2urBeeK6V1YAAAAAAAAAAABQc7xPaiFazKeJjEkqPNi-dMIk3A==" type="text/javascript"></script>

<script type="text/javascript">
    // Создает обработчик события window.onLoad
    YMaps.jQuery(function () {
        // Создает экземпляр карты и привязывает его к созданному контейнеру
        var map = new YMaps.Map(YMaps.jQuery("#YMapsID")[0]);
            
        // Устанавливает начальные параметры отображения карты: центр карты и коэффициент масштабирования
        map.setCenter(new YMaps.GeoPoint(56.027438, 54.77695), 17);
		map.setType(YMaps.MapType.HYBRID);
		map.openBalloon(new YMaps.GeoPoint(56.027298, 54.77707), "Каток");
		
		map.addControl(new YMaps.TypeControl());
		map.addControl(new YMaps.ToolBar());
		map.addControl(new YMaps.Zoom());
		map.addControl(new YMaps.MiniMap());
		map.addControl(new YMaps.ScaleLine());
    })
</script>


<!-- platinum seo pack 1.3.6 -->
<meta name="robots" content="index,follow,noodp,noydir" />
<meta name="keywords" content="каток,каток в уфе,ледовый каток,каток на проспекте,каток в уфе на проспекте,каток в уфе,где покататься в уфе,ледовый каток в уфе,где покататься в уфе,коньки на прокат, ледовый каток в уфе" />
<link rel="canonical" href="/">
<!-- /platinum one seo pack -->
<meta id="syntaxhighlighteranchor" name="syntaxhighlighter-version" content="3.1.1" />

{% if gallery %}
<script src="/media/lb/js/nflb.js" type="text/javascript"></script>
<link href="/media/lb/css/nf.lightbox.css" rel="stylesheet" type="text/css" media="screen" />
<script type='text/javascript'>
  $(document).ready(function () {
    $('.gcontainer a').lightBox();
  });
</script>
{% endif %}

</head>
<body>

<div id="wrap">
   <div id="header">
     <div id="header_top">
	    <div id="logo_slogan">
		 <a href="/" title="КАТОКнаПРОСПЕКТЕ.рф"><img src="{{ MEDIA_URL }}images/ns_logo1.png" alt="Logo" border="0"/></a>
		 <h1 class="slogan">Ледовый каток</h1>
		</div>
		<div id="search_about_box">
		   <div id="search_box_rss">
		      <div id="top_rss"></div>
			  <div id="search_box">
			  <form action="index.html" method="get">
		  <div class="search-box-input">
		 <input type="text" name="s" class="search-text-box"/>
		   </div>
          <div class="search-box-button">
		  <input type="image" src="{{ MEDIA_URL }}images/search_button.png"/>
		  </div>
		</form>
			  </div>
		   </div>
		   <div id="about_us_box">
		     <h2 class="about_heading">Информация: </h2>
			 <p>Этот сайт о катке расположенном в городе Уфа на Проспекте Октября 91а.
			 <br />Спасибо что заглянули!
			 </p>
		   </div>
		   <div id="twitter_box">
		     <a href="" title="Follow Me on Twitter" class="twitter_bird"><img src="{{ MEDIA_URL }}images/twitter_icon_new.png" alt="Snilesh"/></a>
		   </div>
		</div>
	 </div>
	 <div id="navigation_top">
	 	<div class="home-button">
		<a href="/" title="Permanent Link to" class="home-button-hover"><img src="{{ MEDIA_URL }}images/home_mouseover.png" style="margin: 0px 0px 0px 0px; border: none;" alt="post bottom" /></a>
      </div>
		<div class="getq-button">
		<a href="/price/" title="Permanent Link to" class="getq-button-hover"><img src="{{ MEDIA_URL }}images/about_me-mouseover.png" style="margin: 0px 0px 0px 0px; border: none;" alt="post bottom" /></a>
		</div>
		<div class="portfolio-button">
		<a href="/gallery/" title="Permanent Link to" class="portfolio-button-hover"><img src="{{ MEDIA_URL }}images/portfolio_mouseover.png" style="margin: 0px 0px 0px 0px; border: none;" alt="post bottom" /></a>
	   </div>
		<div class="services-button">
		<a href="/contacts/" title="Permanent Link to" class="services-button-hover"><img src="{{ MEDIA_URL }}images/contact-mouseover.png" style="margin: 0px 0px 0px 0px; border: none;" alt="post bottom" /></a>
	   </div>
		<div class="blog-button">
		<a href="/comment/" title="Permanent Link to" class="blog-button-hover"><img src="{{ MEDIA_URL }}images/blog_mouseover.png" style="margin: 0px 0px 0px 0px; border: none;" alt="post bottom" /></a>
		</div>
	 </div>
   </div>

templates/index.html
{% include 'header.html' %}
 <!-- Content All Starts-->  
 <div id="content_all">

   <p><strong>Каток работает в зимнее  время.</strong><br />
     Новое большое и тёплое здание для проката и переобувания коньков. <br />
     Более 200 пар новых коньков  2011 модельного ряда в прокате! <br />
     Большое ледовое поле – более  6000 квадратных метров. <br />
  <br />
  <strong>Расценки сезона 2010/2011</strong>.<br />
     Прокат коньков - 50 руб./час.<br />
     Выход на лед - 100 руб./час.<br />
     Детям до 12 лет (при наличии свидетельства о рождении) – предоставляется скидка  50% на выход на лёд. <br />
  <br />
     Абонемент на 2 недели на  выход на лёд – 800 рублей.<br />
     НОВИНКА!!! Подарочный  абонемент на выход на лёд на сезон 2010/2011 (ограниченная серия) – 2000  рублей. А также розыгрыш абонементов на радио.<br />
  <br />
     Гардероб (обувь принимается в пакетах):<br />
     - при прокате коньков - бесплатно,<br />
     - со своими коньками - 10 руб.<br />
  <br />
     Заточка коньков – 100 руб. <br />
  <br />
     Покатались – подкрепитесь! <br />
     Тёплое кафе - продаются  горячие пирожки, чай, кофе, прохладительные напитки, кислородный коктейль.<br />
  <br />
     Музыкальное сопровождение и гирлянды, создающие праздничное настроение. <br />
     Удобная парковка (въезд со стороны центра – будьте внимательны). <br />
     Возможны скидки на групповое катание. <br />
    Каждую субботу с 11.00 до 13.00 часов игра в хоккей.</p>
<p>&nbsp;</p>
   <p>&nbsp;</p>
 </div>
<!-- Content All Ends-->  
{% include 'footer.html' %}

templates/price.html
{% include 'header.html' %}
 <!-- Content All Starts-->  
 <div id="content_all">

<img width="722" height="100" src="{{ MEDIA_URL }}images/price_clip_image001.gif" alt="НА ЛЕДОВОМ КАТКЕ 'НА ПРОСПЕКТЕ',ПРАВИЛА ПОВЕДЕНИЯ" />

 <ol type="1">
<li>Посетитель ледового катка понимает, что фигурное катание – это травмоопасный вид спорта. Поэтому он сам определяет для себя и своего ребёнка возможность посещения ледового комплекса исходя из физического самочувствия и состояния здоровья. Администрация полностью снимает с себя ответственность в случае получения травм в период нахождения посетителя на территории ледового катка.</li>
<li>Дети до 10 лет допускаются к катанию на ледовом катке только в сопровождении взрослых.</li>
<li>Для детей и неуверенно катающихся взрослых рекомендуется пользоваться защитой – шлемами, налокотниками, наколенниками и напульсниками.</li>
<li>Движение на льду осуществляется по кругу против часовой стрелки. 
<li>Необходимо соблюдать скоростной режим: не катайтесь на большой скорости и не создавайте помехи окружающим.</li>
<li>Соблюдайте время проката коньков и льда. В случае превышения времени катания указанного на билете (кассовом чеке) более чем на 15 минут следует оплатить продление времени катания кратное 30 минутам. 
<li>В случае умышленной порчи имущества ледового катка, виновный должен возместить стоимость испорченного имущества.</li>
<li>Будьте внимательны, аккуратны и взаимно вежливы на льду!</li>
<br />
<img src="{{ MEDIA_URL }}images/price_clip_image002.gif" alt="2" width="298" height="53"/>
<br /><br />
<li>Курить на катке и прилегающих к нему территориях.</li>
<li>Находиться на ледовом катке в нетрезвом состоянии, приносить с собой и распивать спиртные напитки.</li>
<li>Выходить на лёд в состоянии алкогольного или наркотического опьянения и ругаться нецензурными выражениями.</li>
<li>Выходить на ледовое поле в беговых коньках, с клюшками, шайбами, санками, а также без коньков.</li>
<li>Долбить или ковырять лёд коньками или другими предметами, а также бросать на лёд любые предметы, выливать жидкость и сыпать какие-либо вещества.</li>
<li>Приводить с собой на ледовый каток домашних животных.</li>
<li>Играть на катке в хоккей в не отведённое для этого время.</li>
</ol>
     
         
<img src="{{ MEDIA_URL }}images/price_clip_image003.gif" alt="3" width="722" height="100" />
 
   <br/><br/>
   
   <div id="chek" align="center">
 <strong>  Требуйте чек, не отходя от кассы!<br />
     В случае если Вам не дали кассовый чек<br />
    требуйте вернуть деньги!</strong>
    
    </div>
    
    <div class="table_price">
   <table border="0" cellspacing="0" cellpadding="0" >
     <tr>
       <td width="496" valign="top"><p><strong>&nbsp;</strong></p>
         <p><strong>Прокат коньков в час</strong><strong> </strong></p></td>
       <td width="216"><p align="center"><strong>&nbsp;</strong></p>
         <p align="center"><strong>50</strong><strong> рублей</strong><strong> </strong></p></td>
     </tr>
     <tr>
       <td width="496" valign="top"><p><strong>Прокат льда в час </strong><br />
         <strong>- взрослым</strong><br />
         <strong>- детям до 12 лет (при наличии    подтверждающего документа)</strong></p></td>
       <td width="216"><p align="center"><strong>100</strong><strong> рублей</strong><strong> </strong><br />
         <strong>50</strong><strong> рублей</strong></p></td>
     </tr>
     <tr>
       <td width="496" valign="top"><p><strong>Гардероб</strong></p></td>
       <td width="216"><p align="center"><strong>10</strong><strong> рублей</strong></p></td>
     </tr>
     <tr>
       <td width="496" valign="top"><p><strong>Абонемент на прокат льда на 14 дней</strong><br />
         <strong>Подарочный абонемент на весь сезон</strong></p></td>
       <td width="216"><p align="center"><strong>800</strong><strong>   рублей</strong><br />
         <strong>2000</strong><strong> рублей</strong></p></td>
     </tr>
   </table>
  </div>
<br />   <img width="370" height="82" src="{{ MEDIA_URL }}images/price_clip_image004.gif" alt="!!! ВНИМАНИЕ !!!" /><strong>
   <p><strong>&nbsp;</strong></p>
   <br clear="all" />
   <p align="center"><strong>Во избежание конфликтных ситуаций</strong><strong> </strong><br />
     <strong>сохраняйте чек до конца катания.</strong></p>
   <p><strong>Администрация  катка оставляет за собой право отказать в прокате коньков и льда без объяснения  причин!</strong><br />
     <strong>По вопросам  группового катания обращаться к администрации катка! </strong><br />
     <br />
     <strong>Администрация</strong></p>
<p>&nbsp;</p>
   <p>&nbsp;</p>
   <p>&nbsp;</p>
 </div>
<!-- Content All Ends--> 
{% include 'footer.html' %}

templates/search_form.html
<html>
<head>
    <title>Search</title>
</head>
<body>
    <form action="/search/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>